release:
  needs: build
  runs-on: ubuntu-latest

  steps:
  - name: Download built artifact
    uses: actions/download-artifact@v2
    with:
      name: built-exe

  - name: Create GitHub Release
    id: create_release
    uses: actions/github-script@v6
    with:
      script: |
        const { data: release } = await github.repos.createRelease({
          owner: context.repo.owner,
          repo: context.repo.repo,
          tag_name: 'v1.0.0',
          release_name: 'Chillout Tester Release v1.0.0',
          draft: false,
          prerelease: false,
        });
        return release.upload_url;

  - name: Upload .exe to GitHub Release
    uses: actions/upload-release-asset@v1
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: ./chillout_tester.exe
      asset_name: chillout_tester_v1.0.0.exe
      asset_content_type: application/octet-stream