name: Build and Release EXE

permissions:
  contents: write  # Grant write permissions to create releases and upload artifacts

on:
  push:
    branches:
      - release  # Trigger the workflow on push to the release branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build the .exe with custom name using PyInstaller
      run: |
        pyinstaller --onefile --name chillout_tester --hidden-import=ping3 main.py  # Custom name chillout_tester

    - name: Upload built .exe as artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-exe
        path: dist/chillout_tester.exe  # Custom path to the chillout_tester.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download built artifact
      uses: actions/download-artifact@v2
      with:
        name: built-exe
        path: .

    - name: Create GitHub Release
      id: create_release  # Assign ID to reference its outputs
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # You can make this dynamic
        release_name: "Chillout Tester Release v1.0.0"
        draft: false
        prerelease: false

    - name: Upload .exe to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: D:/a/failover_tester/failover_tester/dist/chillout_tester.exe  # Updated to the correct path
        asset_name: chillout_tester_v1.0.0.exe
        asset_content_type: application/octet-stream
